### ISSUE TITLE
Tests Fail to Run on a Package Level

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-clinical#84]
# Issue Description
To fix the heroku slug issue,  the `terra-toolkit` devDependency was removed in each package level. With the removal of this devDependency, test scripts on a package level are resulting in the following error:
> Error: Cannot find module '/Users/er047227/terra-clinical/packages/terra-clinical-item-view/node_modules/terra-toolkit/lib/scripts/nightwatch.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

The tests scripts on a package level uses the following path, which is causing the error: 
`node ./node_modules/terra-toolkit/lib/scripts/nightwatch.js` 

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Steps to Reproduce
1. In any package directory, run `npm run test:nightwatch-default` to produce the error.

**Comment by emilyrohrbough** [comment]
Resolved in #82.
